[package]
name = "wit_owo"
version = "1.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
authors = ["Clifton Toaster Reid"]
description = "A Rust library for the Wit.ai API"
categories = ["api-bindings"]
keywords = ["wit", "wit_ai", "witai"]

[dependencies]
reqwest = { version = "0.12.15", features = ["stream", "json", "native-tls"] }
serde = { version = "1.0.216", features = ["derive", "alloc"] }
serde_json = { version = "1.0.134", features = ["alloc"] }
thiserror = { version = "2.0.9" }
tokio = { version = "1.42.0", features = ["full", "tracing"] }
tracing = { version = "0.1.41", features = ["async-await"] }
lingua = { version = "1.6.2", optional = true }

[features]
multi-lingual = ["dep:lingua"]
