name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us identify and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I am using the latest version of wit_owo
          required: true
        - label: I have read the [documentation](https://github.com/cliftontoaster-reid/wit_owo)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      render: rust
      placeholder: |
        // Your minimal reproducible code here
        use wit_owo::prelude::*;

        fn main() {
            // Code that demonstrates the bug
        }

  - type: textarea
    id: error
    attributes:
      label: Error Messages/Stack Trace
      description: If applicable, provide any error messages or stack traces
      render: shell
      placeholder: Paste any error messages or stack traces here

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (Debian)
        - Linux (Fedora)
        - Linux (Arch)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      description: What architecture are you using?
      options:
        - x86_64
        - ARM64
        - x86
        - Other
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: What version of Rust are you using? (run `rustc --version`)
      placeholder: e.g., rustc 1.79.0 (129f3b996 2024-06-10)
    validations:
      required: true

  - type: input
    id: wit-owo-version
    attributes:
      label: wit_owo Version
      description: What version of wit_owo are you using?
      placeholder: e.g., 1.1.1
    validations:
      required: true

  - type: textarea
    id: cargo-info
    attributes:
      label: Cargo.toml Dependencies
      description: If relevant, please paste the dependencies section from your Cargo.toml
      render: toml
      placeholder: |
        [dependencies]
        wit_owo = "1.1.1"
        # other dependencies...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as logs, screenshots, or configuration files
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: confidentiality
    attributes:
      label: Security Notice
      description: Security-related bugs should be reported privately
      options:
        - label: This bug report does not contain sensitive information or security vulnerabilities
          required: true
