name: ✨ Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your feature request
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have read the [documentation](https://github.com/cliftontoaster-reid/wit_owo)
          required: true
        - label: This feature would be useful to the majority of wit_owo users, not just a small subset
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches have you thought about?

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: If applicable, provide examples of how this feature would be used
      render: rust
      placeholder: |
        // Example usage of the proposed feature
        use wit_owo::prelude::*;

        fn main() {
            // How the new feature would be used
        }

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this feature provide to wit_owo users?
      placeholder: |
        - Improved performance
        - Better developer experience
        - New capabilities
        - etc.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, please share them
      placeholder: Optional implementation suggestions or technical considerations

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
      placeholder: Any additional information that might be helpful...
