name: Rust Continuous Testing Integration
on:
  push:
    branches: [main]
    paths:
      - src/**
      - Cargo.toml
      - Cargo.lock
      - assets/**
      - .trunk/**
      - .github/workflows/rust.yml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - Cargo.toml
      - Cargo.lock
      - assets/**
      - .trunk/**
      - .github/workflows/rust.yml
permissions:
  contents: write # allow commits+pushing
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install DENO
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Set up Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          override: true
          components: clippy

      - name: Cache cargo target directory
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Run comprehensive tests with Deno script
        run: deno run --allow-read --allow-run publish.ts
        working-directory: tools/
        env:
          WIT_API_TOKEN: ${{ secrets.WIT_API_TOKEN }}
