name: Rust Continuous Testing Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: write # allow commits+pushing
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Rust
        uses: actions-rs/toolchain@v2
        with:
          toolchain: nightly
          override: true
          components: clippy

      - name: Install dependencies
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
        env:
          WIT_API_TOKEN: ${{ secrets.WIT_API_TOKEN }}

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true # so git push is allowed
          fetch-depth: 0 # full history for safe rebasing, etc.

      - name: Set up Rust
        uses: actions-rs/toolchain@v2
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Cache cargo-msrv binary
        uses: actions/cache@v5
        id: msrv-cache
        with:
          path: ~/.cargo/bin/cargo-msrv
          key: ${{ runner.os }}-cargo-msrv

      - name: Install cargo-msrv (if not cached)
        if: steps.msrv-cache.outputs.cache-hit != 'true'
        run: cargo install cargo-msrv

      - name: Find and set MSRV
        run: |
          set -o pipefail
          # run find, grab the version after “MSRV:”
          MSRV=$(cargo msrv find --include-all-patch-releases 2>&1 \
                | awk '/MSRV:/ {print $2}' \
                | sed -E 's/\x1B\[[0-9;]*[mK]//g')
          echo "🕵️ Detected MSRV: $MSRV"
          # now set it
          cargo msrv set "$MSRV"
      - name: Install Trunk CLI
        run: |
          curl -LO https://trunk.io/releases/trunk
          chmod +x trunk
          mkdir -p "$HOME/.cargo/bin"
          mv trunk "$HOME/.cargo/bin"

      - name: Format code with Trunk
        run: trunk fmt

      - name: Commit and push MSRV update
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: update MSRV to $MSRV"
          git push
